name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install JSHint
      run: npm install jshint --global

    - name: Run Linter
      run: |
        # Create .jshintrc if it doesn't exist
        echo '{"esversion": 8, "node": true, "asi": true}' > ./giftlink-backend/.jshintrc
        
        # Run JSHint with config file
        find ./giftlink-backend -name "*.js" -not -path "./giftlink-backend/node_modules/*" -exec jshint --config ./giftlink-backend/.jshintrc {} +
        echo "Linted all the js files successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Run build
      run: |
        cd giftlink-frontend
        npm install
        npm run build
        echo "Client-side build successfully"
